[workspace]
resolver = "2"
members = ["mini-query", "mini-query-derive"]

[workspace.package]
name = "mini-query"
version = "0.1.6"

[workspace.dependencies]
convert_case = "0.6"
syn = "2"
proc-macro2 = "1"
quote = "1"
